import type { PackageDefinition, PlanningScenario, PlanningWorkspace, ScenarioComparison, ScenarioCostResult } from "../../planning/types";
import { buildPlannerEstimate, comparePlannerEstimates } from "../../planning/plannerPresentation";
import { getScenarioReviewStatus } from "../../planning/planningWorkspace";

export interface PlanningViewModel {
  state: string;
  workspace: PlanningWorkspace | null;
  workspaces: PlanningWorkspace[];
  scenario: PlanningScenario | null;
  cost: ScenarioCostResult | null;
  comparison: ScenarioComparison | null;
  compareId: string;
  recipes: readonly PackageDefinition[];
  message: string;
  dirty: boolean;
  busy: boolean;
  readOnly: boolean;
  persistent: boolean;
  updatePreview?: { instanceId: string; beforeAmount: number | null; afterAmount: number | null; beforeLabel: string; afterLabel: string } | null;
}

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const money = (value: number | null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const number = (value: number | null | undefined) => value === null || value === undefined ? "" : String(value);
const option = (value: string, label: string, selected: boolean) => `<option value="${escape(value)}" ${selected ? "selected" : ""}>${escape(label)}</option>`;
const field = (label: string, fieldName: string, value: unknown, more = "", type = "text") => `<label class="planning-field"><span>${escape(label)}</span><input type="${type === "number" ? "text" : type}" ${type === "number" ? 'inputmode="decimal"' : ""} data-field="${fieldName}" ${more} value="${escape(value)}"></label>`;

function packageMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  return scenario.packages.map((instance) => {
    const components = cost.components.filter((entry) => entry.instanceId === instance.instanceId);
    const parameters = instance.definition.parameters.map((parameter) => {
      const override = instance.parameterOverrides[parameter.key];
      return `<label class="planning-field"><span>${escape(parameter.label)} (${escape(parameter.unit)})</span><input type="text" inputmode="decimal" data-field="parameter" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" value="${escape(number(override ? override.value : parameter.defaultValue))}"><small>Default: ${escape(number(parameter.defaultValue))}. ${escape(parameter.assumption.description)}</small><input type="text" aria-label="Reason for ${escape(parameter.label)}" data-field="override-reason" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" data-kind="parameter" value="${escape(override?.reason ?? "Planner-adjusted provisional assumption")}"></label>`;
    }).join("");
    const rows = components.map((component) => {
      const snapshot = instance.rateSnapshots[component.role];
      const override = instance.rateOverrides[component.role];
      const quantity = instance.quantityOverrides[component.role];
      const price = component.rateBasis?.kind === "ne_annual" ? `NDOT annual average ${escape(component.rateBasis.periodStart)}–${escape(component.rateBasis.periodEnd)}` : component.rateBasis?.kind === "co_contract_median" ? `CDOT cost-book awarded median across ${component.rateBasis.contracts.length} contracts` : component.rateBasis?.kind === "manual" ? `Manual: ${escape(component.rateBasis.reason)}` : "No price basis";
      const rateControls = component.binding ? scenario.state === "NE" ? `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}"><label class="planning-field"><span>NDOT report series</span><select data-rate="series">${option("calendar_year", "Calendar year", snapshot?.kind !== "ne_annual" || snapshot.reportSeries === "calendar_year")}${option("july_june", "July–June", snapshot?.kind === "ne_annual" && snapshot.reportSeries === "july_june")}</select></label>${field("Report start (optional)", "rate-period-start", snapshot?.kind === "ne_annual" ? snapshot.periodStart : "", `data-rate="period-start"`, "date")}${field("Report end (optional)", "rate-period-end", snapshot?.kind === "ne_annual" ? snapshot.periodEnd : "", `data-rate="period-end"`, "date")}</div>` : `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}">${field("CDOT from date", "rate-from", snapshot?.kind === "co_contract_median" ? snapshot.requestedFrom : "", `data-rate="from"`, "date")}${field("CDOT through date", "rate-to", snapshot?.kind === "co_contract_median" ? snapshot.requestedTo : "", `data-rate="to"`, "date")}${field("Districts (comma separated)", "rate-districts", snapshot?.kind === "co_contract_median" ? snapshot.districts.join(", ") : "", `data-rate="districts"`)}${field("Source IDs (comma separated)", "rate-sources", snapshot?.kind === "co_contract_median" ? snapshot.requestedSourceIds.join(", ") : "", `data-rate="sources"`)}</div>` : "";
      return `<tr class="planning-component planning-${escape(component.status)}"><td>${escape(component.description)}<small>${escape(component.binding?.agencyItemId ?? "Manual scope")} · ${price}</small></td><td>${escape(number(component.quantity))} ${escape(component.unit)}<small>Original ${escape(number(component.originalQuantity))}</small></td><td>${money(component.rate)}</td><td>${money(component.extendedCost)}</td><td>${escape(component.status)}</td></tr>
        <tr class="planning-edit-row"><td colspan="5"><div class="planning-grid">${field("Quantity override", "quantity", number(quantity?.value), `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`, "number")}${field("Quantity reason", "override-reason", quantity?.reason ?? "Planner-adjusted provisional assumption", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" data-kind="quantity"`)}${field("Manual unit rate", "rate", number(override?.value), `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`, "number")}${field("Rate reason", "override-reason", override?.reason ?? "Planner-adjusted provisional assumption", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" data-kind="rate"`)}<label class="planning-field"><span>Exclude from scope</span><input type="checkbox" data-field="exclude" data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" ${instance.exclusions[component.role] ? "checked" : ""}></label>${field("Exclusion reason", "exclusion-reason", instance.exclusions[component.role]?.reason ?? "Excluded by planner", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`)}${field("Section effect", "exclusion-effect", instance.exclusions[component.role]?.sectionEffect ?? "Remove this component from planned scope", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`)}</div><small>${snapshot ? `Frozen source: ${escape(snapshot.kind === "ne_annual" ? `${snapshot.sourceDescription}; ${snapshot.sourceUrl}; ${snapshot.sourceLocator}; ${snapshot.inflation.availability}` : `${snapshot.actualFrom}–${snapshot.actualTo}; ${snapshot.contracts.length} contracts; ${snapshot.inflation.availability}`)}` : "No exact source rate available."} ${component.issues.map((issue) => escape(issue.message)).join(" ")}</small>${rateControls}${component.binding ? `<button type="button" class="planning-link" data-action="refresh-rate" data-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}">Apply selected source rate</button>` : ""}</td></tr>`;
    }).join("");
    return `<section class="planning-card"><div class="planning-card-heading"><div><h3>${escape(instance.definition.name)}</h3><p>Provisional ${escape(instance.definition.version)}</p></div><button type="button" class="planning-link" data-action="remove-package" data-id="${escape(instance.instanceId)}">Remove</button></div><details data-detail="package-${escape(instance.instanceId)}"><summary>Geometry, section and assumptions</summary><div class="planning-grid">${parameters}</div><ul>${instance.definition.assumptions.map((assumption) => `<li>${escape(assumption.description)}</li>`).join("")}</ul><p>Excluded by recipe: ${escape(instance.definition.exclusions.join("; "))}</p></details><div class="planning-table-wrap"><table><thead><tr><th>Component and basis</th><th>Quantity</th><th>Rate</th><th>Cost</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
  }).join("");
}

function customMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  return scenario.customComponents.map((component) => {
    const calculated = cost.components.find((entry) => entry.componentId === component.componentId);
    return `<div class="planning-card planning-custom"><div class="planning-grid">${field("Description", "custom-description", component.description, `data-id="${escape(component.componentId)}"`)}${field("Quantity", "custom-quantity", number(component.quantity), `data-id="${escape(component.componentId)}"`, "number")}${field("Unit rate", "custom-unitRate", number(component.unitRate), `data-id="${escape(component.componentId)}"`, "number")}${field("Reason / source", "custom-reason", component.reason, `data-id="${escape(component.componentId)}"`)}</div><p>${escape(component.unit)} · ${escape(calculated?.status ?? "unpriced")} · ${money(calculated?.extendedCost ?? null)} <button type="button" class="planning-link" data-action="remove-custom" data-id="${escape(component.componentId)}">Remove</button></p></div>`;
  }).join("");
}

function parameterValue(instance: PlanningScenario["packages"][number] | undefined, key: string) {
  if (!instance) return null;
  const override = instance.parameterOverrides[key];
  return override ? override.value : instance.definition.parameters.find((parameter) => parameter.key === key)?.defaultValue ?? null;
}

const packageLabel = (kind: string) => ({ resurfacing: "Asphalt resurfacing", reconstruction: "Concrete reconstruction", path: "Concrete path", sidewalk: "Concrete sidewalk" })[kind] ?? kind;

function scenarioMarkup(view: PlanningViewModel) {
  const scenario = view.scenario!;
  const cost = view.cost!;
  const estimate = buildPlannerEstimate(scenario, cost);
  const base = scenario.packages.find((instance) => instance.definition.kind !== "sidewalk");
  const sidewalk = scenario.packages.find((instance) => instance.definition.kind === "sidewalk");
  const baseId = `data-instance-id="${escape(base?.instanceId ?? "")}"`;
  const sidewalkId = `data-instance-id="${escape(sidewalk?.instanceId ?? "")}"`;
  const section = base ? base.definition.parameters.filter((parameter) => ["thicknessIn", "baseDepthIn"].includes(parameter.key)).map((parameter) => `${number(parameterValue(base, parameter.key))} inch ${parameter.key === "thicknessIn" ? (base.definition.kind === "resurfacing" ? "asphalt" : "concrete") : "base"}`).join(" over ") : "Choose an improvement to start.";
  const external = scenario.externalScopes.map((scope) => `<label class="planning-field"><span>${scope.scopeId === "right_of_way" ? "Property acquisition" : "Major utility relocation"}</span><select data-field="external-decision" data-id="${escape(scope.scopeId)}">${option("none_assumed", "None expected", scope.decision === "none_assumed")}${option("unassessed", "Possible / unknown", scope.decision === "unassessed")}${option("manual", "Known impact", scope.decision === "manual")}</select></label>`).join("");
  const externalAdvanced = scenario.externalScopes.map((scope) => `<div class="planning-grid">${field(scope.scopeId === "right_of_way" ? "Property acquisition amount" : "Major utility amount", "external-amount", number(scope.amount), `data-id="${escape(scope.scopeId)}" ${scope.decision !== "manual" ? "disabled" : ""}`, "number")}${field("Scope decision reason", "external-reason", scope.reason || "Planner-assessed external scope", `data-id="${escape(scope.scopeId)}"`)}</div>`).join("");
  const allowanceRows = scenario.allowances.map((allowance) => {
    const calculated = cost.allowances.find((entry) => entry.allowanceId === allowance.allowanceId);
    return `<tr><td>${escape(allowance.name)}<small>${escape(allowance.assumption.description)}</small>${field("Change reason", "allowance-reason", allowance.overrideReason ?? "Engineer-adjusted provisional assumption", `data-id="${escape(allowance.allowanceId)}"`)}</td><td><input aria-label="Include ${escape(allowance.name)}" type="checkbox" data-field="allowance-enabled" data-id="${escape(allowance.allowanceId)}" ${allowance.enabled ? "checked" : ""}></td><td><input aria-label="${escape(allowance.name)} percent" type="text" inputmode="decimal" data-field="allowance-percent" data-id="${escape(allowance.allowanceId)}" value="${escape(number(allowance.percent))}"></td><td>${escape(calculated?.status ?? "unpriced")}</td><td>${money(calculated?.amount ?? null)}</td></tr>`;
  }).join("");
  const other = view.workspace!.scenarios.find((entry) => entry.scenarioId === view.compareId);
  const comparisonEstimate = other && view.comparison ? buildPlannerEstimate(other, view.comparison.right) : null;
  const difference = comparisonEstimate ? comparePlannerEstimates(estimate, comparisonEstimate) : null;
  const comparison = comparisonEstimate ? `<div class="planning-comparison"><strong>${escape(other!.name)}: ${money(comparisonEstimate.amount)}</strong><p>${difference === null ? "Included or excluded work differs. Review coverage before comparing costs." : `Difference for the same included work: ${money(difference)}`}</p></div>` : "";
  const updates = scenario.packages.filter((instance) => view.recipes.some((recipe) => recipe.kind === instance.definition.kind && recipe.version !== instance.definition.version)).map((instance) => `<details class="planning-package-update"><summary>${escape(packageLabel(instance.definition.kind))}: package update available</summary><p>Saved prices and quantities stay frozen until you apply a reviewed update.</p><button type="button" data-action="preview-package-update" data-id="${escape(instance.instanceId)}">Preview revised package</button>${view.updatePreview?.instanceId === instance.instanceId ? `<p>Current ${escape(view.updatePreview.beforeLabel)}: ${money(view.updatePreview.beforeAmount)}<br>Revised ${escape(view.updatePreview.afterLabel)}: ${money(view.updatePreview.afterAmount)}</p><button type="button" data-action="adopt-package-update" data-id="${escape(instance.instanceId)}">Use revised package</button>` : ""}</details>`).join("");
  const notices = estimate.notices.slice(0, 4);
  return `<div class="planning-toolbar planning-alternative"><label class="planning-field"><span>Alternative</span><select data-field="scenario-select">${view.workspace!.scenarios.map((entry) => option(entry.scenarioId, entry.name, entry.scenarioId === scenario.scenarioId)).join("")}</select></label><button type="button" data-action="duplicate">Compare an alternative</button></div>
    <div class="planning-layout"><div class="planning-main">
    <section class="planning-section"><h2>Project basics</h2><div class="planning-grid"><label class="planning-field"><span>Improvement type</span><select data-field="base-kind">${option("", "Choose improvement", !base)}${view.recipes.filter((recipe) => recipe.kind !== "sidewalk").map((recipe) => option(recipe.kind, packageLabel(recipe.kind), recipe.kind === base?.definition.kind)).join("")}</select></label>${field("Length (miles)", "planner-length", number(parameterValue(base, "lengthMiles")), `${baseId} ${!base ? "disabled" : ""}`, "number")}${field(base?.definition.kind === "path" ? "Path width (feet)" : "Roadway width (feet)", "planner-width", number(parameterValue(base, "widthFt")), `${baseId} ${!base ? "disabled" : ""}`, "number")}${field("Roadway setting / location (optional)", "location", scenario.location)}<small>Descriptive only; does not change cost.</small></div></section>
    <section class="planning-section"><h2>Base package</h2><p>${escape(base ? packageLabel(base.definition.kind) : "No improvement selected")} · ${escape(section)}</p>${base ? `<p>${escape(base.definition.components.map((component) => component.description).join("; "))}.</p><details data-detail="quantity-assumptions"><summary>See quantity assumptions</summary><ul>${base.definition.parameters.map((parameter) => `<li>${escape(parameter.label)}: ${escape(number(parameterValue(base, parameter.key)))} ${escape(parameter.unit)}</li>`).join("")}</ul></details>` : ""}</section>
    <section class="planning-section"><h2>Add project elements</h2><label class="planning-checkbox"><input type="checkbox" data-field="sidewalk-enabled" ${sidewalk ? "checked" : ""} ${!base ? "disabled" : ""}> Include sidewalk</label>${sidewalk ? `<div class="planning-grid"><label class="planning-field"><span>Sidewalk sides</span><select data-field="sidewalk-sides" ${sidewalkId}>${option("1", "One side", parameterValue(sidewalk, "sides") === 1)}${option("2", "Both sides", parameterValue(sidewalk, "sides") === 2)}</select></label>${field("Width per side (feet)", "sidewalk-width", number(parameterValue(sidewalk, "widthFt")), sidewalkId, "number")}${field("Approximate curb ramp count", "ramp-count", number(parameterValue(sidewalk, "rampCount")), sidewalkId, "number")}</div><p class="planning-muted">Driveway crossings and intermediate crossing work require engineer review.</p>` : ""}<button type="button" class="planning-link" data-action="add-custom" ${!base ? "disabled" : ""}>Other work to include</button>${scenario.customComponents.map((component) => `<div class="planning-grid">${field("Other work description", "custom-description", component.description, `data-id="${escape(component.componentId)}"`)}${field("Rough quantity (optional)", "custom-quantity", number(component.quantity), `data-id="${escape(component.componentId)}"`, "number")}<small>Engineer price required.</small></div>`).join("")}</section>
    </div><aside class="planning-estimate planning-section" aria-label="Estimate summary"><h2>Estimate summary</h2><span class="planning-provisional">Provisional planning prices</span><dl><div><dt>Priced construction</dt><dd>${money(estimate.construction)}</dd></div><div><dt>Other project costs</dt><dd>${money(estimate.otherProjectCosts)}</dd></div><div class="planning-estimate-total"><dt>${escape(estimate.amountLabel)}</dt><dd>${money(estimate.amount)}</dd></div></dl>${estimate.excludedScope.length ? `<p class="planning-scope"><strong>Excludes:</strong> ${escape(estimate.excludedScope.join("; "))}.</p>` : ""}<p class="planning-muted">Order-of-magnitude estimate. Engineer review is required.</p><div class="planning-external">${external}</div><label class="planning-field"><span>Compare with</span><select data-field="compare-select">${option("", "Select alternative", !view.compareId)}${view.workspace!.scenarios.filter((entry) => entry.scenarioId !== scenario.scenarioId).map((entry) => option(entry.scenarioId, entry.name, view.compareId === entry.scenarioId)).join("")}</select></label>${comparison}</aside></div>
    <section class="planning-section"><h2>For engineer review</h2>${notices.length ? `<ul class="planning-notices">${notices.map((notice) => `<li><strong>${notice.kind === "price" ? "Price" : notice.kind === "scope" ? "Scope" : "Evidence"}:</strong> ${escape(notice.text)}</li>`).join("")}</ul>${estimate.notices.length > notices.length ? `<p class="planning-muted">${estimate.notices.length - notices.length} additional decisions in advanced assumptions.</p>` : ""}` : `<p>Confirm the typical section, provisional prices and included scope.</p>`}
    <details class="planning-advanced"><summary>Engineer review / advanced assumptions</summary><div class="planning-advanced-content"><div class="planning-grid">${field("Alternative name", "name", scenario.name)}</div><label class="planning-field"><span>Notes</span><textarea data-field="notes">${escape(scenario.notes)}</textarea></label>${updates}${packageMarkup(scenario, cost)}${customMarkup(scenario, cost)}<h3>Other project cost assumptions</h3><div class="planning-table-wrap"><table><thead><tr><th>Allowance</th><th>Use</th><th>Percent</th><th>Status</th><th>Amount</th></tr></thead><tbody>${allowanceRows}</tbody></table></div>${externalAdvanced}<p>Review status: ${escape(getScenarioReviewStatus(scenario))}</p><div class="planning-grid">${field("Reviewer", "reviewer", scenario.review?.reviewer ?? "")}${field("Review date", "review-date", scenario.review?.date ?? new Date().toISOString().slice(0, 10), "", "date")}</div><label class="planning-field"><span>Review notes</span><textarea data-field="review-notes">${escape(scenario.review?.notes ?? "")}</textarea></label><button type="button" data-action="review">Record review</button><details><summary>All review decisions (${estimate.notices.length})</summary><ul>${estimate.notices.map((notice) => `<li>${escape(notice.text)}</li>`).join("")}</ul></details></div></details></section>`;
}

export function renderPlanningWorkspace(root: HTMLElement, view: PlanningViewModel) {
  if (view.state !== "NE" && view.state !== "CO") { root.innerHTML = `<div class="planning-panel"><h1>Planning</h1><p>The Planning pilot is available for Nebraska and Colorado.</p></div>`; return; }
  const creation = `<div class="planning-grid">${field("Planning project name", "new-project-name", "")}<button type="button" data-action="create-workspace" ${view.busy || view.readOnly ? "disabled" : ""}>Create planning project</button></div>`;
  const saved = view.message || (view.dirty ? "Unsaved changes" : view.persistent ? "Saved in this browser" : "Browser storage unavailable; save a recovery file");
  root.innerHTML = `<div class="planning-panel"><header class="planning-header"><div><h1>Planning${view.workspace ? ` · ${escape(view.workspace.name)}` : ""}</h1><p>${view.state === "NE" ? "Nebraska" : "Colorado"} planning estimate</p></div><details class="planning-actions"><summary>Project actions</summary><div class="planning-actions-content"><label class="planning-field"><span>Planning project</span><select data-field="workspace-select">${view.workspaces.map((entry) => option(entry.workspaceId, entry.name, entry.workspaceId === view.workspace?.workspaceId)).join("")}</select></label>${view.workspace ? creation : ""}<button type="button" data-action="save" ${!view.dirty || view.readOnly ? "disabled" : ""}>Save changes</button><button type="button" data-action="export-json" ${!view.workspace ? "disabled" : ""}>Save recovery JSON</button><button type="button" data-action="import-json">Import recovery JSON</button><button type="button" data-action="export-csv" ${!view.scenario ? "disabled" : ""}>Export cost review CSV</button></div></details><input type="file" accept="application/json,.json" data-field="import-file" hidden></header><p class="planning-message" role="status">${escape(saved)}</p>${view.readOnly ? `<div class="planning-card"><strong>Read only: another tab is editing this planning project.</strong> <button type="button" data-action="take-over">Take over editing</button></div>` : ""}<fieldset class="planning-editing" ${view.readOnly ? "disabled" : ""}>${view.workspace ? view.scenario && view.cost ? scenarioMarkup(view) : `<div class="planning-card"><p>Add an alternative to start estimating.</p><button type="button" data-action="create-scenario">Create Alternative A</button></div>` : `<section class="planning-section"><h2>Create a planning project</h2><p>Start with a project name. Then select the improvement and approximate length.</p>${creation}</section>`}</fieldset></div>`;
}
