import type { PackageDefinition, PlanningScenario, PlanningWorkspace, ScenarioComparison, ScenarioCostResult } from "../../planning/types";
import { getScenarioReviewStatus } from "../../planning/planningWorkspace";

export interface PlanningViewModel {
  state: string;
  workspace: PlanningWorkspace | null;
  workspaces: PlanningWorkspace[];
  scenario: PlanningScenario | null;
  cost: ScenarioCostResult | null;
  comparison: ScenarioComparison | null;
  compareId: string;
  recipes: readonly PackageDefinition[];
  message: string;
  dirty: boolean;
  busy: boolean;
  readOnly: boolean;
  persistent: boolean;
}

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const money = (value: number | null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const number = (value: number | null | undefined) => value === null || value === undefined ? "" : String(value);
const option = (value: string, label: string, selected: boolean) => `<option value="${escape(value)}" ${selected ? "selected" : ""}>${escape(label)}</option>`;
const field = (label: string, fieldName: string, value: unknown, more = "", type = "text") => `<label class="planning-field"><span>${escape(label)}</span><input type="${type === "number" ? "text" : type}" ${type === "number" ? 'inputmode="decimal"' : ""} data-field="${fieldName}" ${more} value="${escape(value)}"></label>`;

function packageMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  return scenario.packages.map((instance) => {
    const components = cost.components.filter((entry) => entry.instanceId === instance.instanceId);
    const parameters = instance.definition.parameters.map((parameter) => {
      const override = instance.parameterOverrides[parameter.key];
      return `<label class="planning-field"><span>${escape(parameter.label)} (${escape(parameter.unit)})</span><input type="text" inputmode="decimal" data-field="parameter" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" value="${escape(number(override ? override.value : parameter.defaultValue))}"><small>Default: ${escape(number(parameter.defaultValue))}. ${escape(parameter.assumption.description)}</small><input type="text" aria-label="Reason for ${escape(parameter.label)}" data-field="override-reason" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" data-kind="parameter" value="${escape(override?.reason ?? "Planner-adjusted provisional assumption")}"></label>`;
    }).join("");
    const rows = components.map((component) => {
      const snapshot = instance.rateSnapshots[component.role];
      const override = instance.rateOverrides[component.role];
      const quantity = instance.quantityOverrides[component.role];
      const price = component.rateBasis?.kind === "ne_annual" ? `NDOT annual average ${escape(component.rateBasis.periodStart)}–${escape(component.rateBasis.periodEnd)}` : component.rateBasis?.kind === "co_contract_median" ? `CDOT cost-book awarded median across ${component.rateBasis.contracts.length} contracts` : component.rateBasis?.kind === "manual" ? `Manual: ${escape(component.rateBasis.reason)}` : "No price basis";
      const rateControls = component.binding ? scenario.state === "NE" ? `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}"><label class="planning-field"><span>NDOT report series</span><select data-rate="series">${option("calendar_year", "Calendar year", snapshot?.kind !== "ne_annual" || snapshot.reportSeries === "calendar_year")}${option("july_june", "July–June", snapshot?.kind === "ne_annual" && snapshot.reportSeries === "july_june")}</select></label>${field("Report start (optional)", "rate-period-start", snapshot?.kind === "ne_annual" ? snapshot.periodStart : "", `data-rate="period-start"`, "date")}${field("Report end (optional)", "rate-period-end", snapshot?.kind === "ne_annual" ? snapshot.periodEnd : "", `data-rate="period-end"`, "date")}</div>` : `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}">${field("CDOT from date", "rate-from", snapshot?.kind === "co_contract_median" ? snapshot.requestedFrom : "", `data-rate="from"`, "date")}${field("CDOT through date", "rate-to", snapshot?.kind === "co_contract_median" ? snapshot.requestedTo : "", `data-rate="to"`, "date")}${field("Districts (comma separated)", "rate-districts", snapshot?.kind === "co_contract_median" ? snapshot.districts.join(", ") : "", `data-rate="districts"`)}${field("Source IDs (comma separated)", "rate-sources", snapshot?.kind === "co_contract_median" ? snapshot.requestedSourceIds.join(", ") : "", `data-rate="sources"`)}</div>` : "";
      return `<tr class="planning-component planning-${escape(component.status)}"><td>${escape(component.description)}<small>${escape(component.binding?.agencyItemId ?? "Manual scope")} · ${price}</small></td><td>${escape(number(component.quantity))} ${escape(component.unit)}<small>Original ${escape(number(component.originalQuantity))}</small></td><td>${money(component.rate)}</td><td>${money(component.extendedCost)}</td><td>${escape(component.status)}</td></tr>
        <tr class="planning-edit-row"><td colspan="5"><div class="planning-grid">${field("Quantity override", "quantity", number(quantity?.value), `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`, "number")}${field("Quantity reason", "override-reason", quantity?.reason ?? "Planner-adjusted provisional assumption", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" data-kind="quantity"`)}${field("Manual unit rate", "rate", number(override?.value), `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`, "number")}${field("Rate reason", "override-reason", override?.reason ?? "Planner-adjusted provisional assumption", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" data-kind="rate"`)}<label class="planning-field"><span>Exclude from scope</span><input type="checkbox" data-field="exclude" data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}" ${instance.exclusions[component.role] ? "checked" : ""}></label>${field("Exclusion reason", "exclusion-reason", instance.exclusions[component.role]?.reason ?? "Excluded by planner", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`)}${field("Section effect", "exclusion-effect", instance.exclusions[component.role]?.sectionEffect ?? "Remove this component from planned scope", `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`)}</div><small>${snapshot ? `Frozen source: ${escape(snapshot.kind === "ne_annual" ? `${snapshot.sourceDescription}; ${snapshot.sourceUrl}; ${snapshot.sourceLocator}; ${snapshot.inflation.availability}` : `${snapshot.actualFrom}–${snapshot.actualTo}; ${snapshot.contracts.length} contracts; ${snapshot.inflation.availability}`)}` : "No exact source rate available."} ${component.issues.map((issue) => escape(issue.message)).join(" ")}</small>${rateControls}${component.binding ? `<button type="button" class="planning-link" data-action="refresh-rate" data-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}">Apply selected source rate</button>` : ""}</td></tr>`;
    }).join("");
    return `<section class="planning-card"><div class="planning-card-heading"><div><h3>${escape(instance.definition.name)}</h3><p>Provisional ${escape(instance.definition.version)} · Segment ${escape(scenario.segments.find((entry) => entry.segmentId === instance.segmentId)?.name ?? instance.segmentId)} · Scope ${escape(instance.scopeId)}</p></div><button type="button" class="planning-link" data-action="remove-package" data-id="${escape(instance.instanceId)}">Remove</button></div><details><summary>Geometry, section and assumptions</summary><div class="planning-grid">${parameters}</div><ul>${instance.definition.assumptions.map((assumption) => `<li>${escape(assumption.description)}</li>`).join("")}</ul><p>Excluded by recipe: ${escape(instance.definition.exclusions.join("; "))}</p></details><div class="planning-table-wrap"><table><thead><tr><th>Component and basis</th><th>Quantity</th><th>Rate</th><th>Cost</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
  }).join("");
}

function customMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  return scenario.customComponents.map((component) => {
    const calculated = cost.components.find((entry) => entry.componentId === component.componentId);
    return `<div class="planning-card planning-custom"><div class="planning-grid">${field("Description", "custom-description", component.description, `data-id="${escape(component.componentId)}"`)}${field("Quantity", "custom-quantity", number(component.quantity), `data-id="${escape(component.componentId)}"`, "number")}${field("Unit rate", "custom-unitRate", number(component.unitRate), `data-id="${escape(component.componentId)}"`, "number")}${field("Reason / source", "custom-reason", component.reason, `data-id="${escape(component.componentId)}"`)}</div><p>${escape(component.unit)} · ${escape(calculated?.status ?? "unpriced")} · ${money(calculated?.extendedCost ?? null)} <button type="button" class="planning-link" data-action="remove-custom" data-id="${escape(component.componentId)}">Remove</button></p></div>`;
  }).join("");
}

function scenarioMarkup(view: PlanningViewModel) {
  const scenario = view.scenario!; const cost = view.cost!;
  const allowanceRows = scenario.allowances.map((allowance) => {
    const calculated = cost.allowances.find((entry) => entry.allowanceId === allowance.allowanceId);
    return `<tr><td>${escape(allowance.name)}<small>${escape(allowance.assumption.description)}</small><input type="text" aria-label="Reason for ${escape(allowance.name)} change" data-field="allowance-reason" data-id="${escape(allowance.allowanceId)}" value="${escape(allowance.overrideReason ?? "Planner-adjusted provisional assumption")}"></td><td><input type="checkbox" data-field="allowance-enabled" data-id="${escape(allowance.allowanceId)}" ${allowance.enabled ? "checked" : ""}></td><td><input type="text" inputmode="decimal" data-field="allowance-percent" data-id="${escape(allowance.allowanceId)}" value="${escape(number(allowance.percent))}"></td><td>${escape(calculated?.status ?? "unpriced")}</td><td>${money(calculated?.amount ?? null)}</td></tr>`;
  }).join("");
  const external = scenario.externalScopes.map((scope) => `<div class="planning-grid planning-external"><label class="planning-field"><span>${scope.scopeId === "right_of_way" ? "Right of way" : "Major utilities"}</span><select data-field="external-decision" data-id="${escape(scope.scopeId)}">${option("unassessed", "Unassessed", scope.decision === "unassessed")}${option("none_assumed", "None assumed", scope.decision === "none_assumed")}${option("manual", "Manual allowance", scope.decision === "manual")}</select></label>${field("Amount", "external-amount", number(scope.amount), `data-id="${escape(scope.scopeId)}" ${scope.decision !== "manual" ? "disabled" : ""}`, "number")}${field("Decision reason", "external-reason", scope.reason || "Planner-assessed external scope", `data-id="${escape(scope.scopeId)}"`)}</div>`).join("");
  const compareOptions = view.workspace!.scenarios.filter((entry) => entry.scenarioId !== scenario.scenarioId).map((entry) => option(entry.scenarioId, entry.name, view.compareId === entry.scenarioId)).join("");
  const comparison = view.comparison ? `<div class="planning-card"><strong>Priced direct difference: ${money(view.comparison.pricedDirectDifference)}</strong><p>Full total difference: ${view.comparison.comparableCompleteTotals ? money(view.comparison.totalDifference) : "Unavailable while either scenario is incomplete"}</p><details><summary>Changed assumptions (${view.comparison.changes.length})</summary><ul>${view.comparison.changes.map((change) => `<li>${escape(change.path)}: ${escape(JSON.stringify(change.before))} → ${escape(JSON.stringify(change.after))}</li>`).join("")}</ul></details></div>` : "";
  return `<div class="planning-toolbar"><label>Scenario <select data-field="scenario-select">${view.workspace!.scenarios.map((entry) => option(entry.scenarioId, entry.name, entry.scenarioId === scenario.scenarioId)).join("")}</select></label><button type="button" data-action="create-scenario">New scenario</button><button type="button" data-action="duplicate">Duplicate scenario</button><button type="button" data-action="export-csv">Cost review CSV</button></div>
    <div class="planning-card"><div class="planning-grid">${field("Scenario name", "name", scenario.name)}${field("Location", "location", scenario.location)}</div><label class="planning-field"><span>Notes</span><textarea data-field="notes">${escape(scenario.notes)}</textarea></label></div>
    <div class="planning-summary"><div><span>Known priced direct</span><strong>${money(cost.pricedDirectSubtotal)}</strong></div><div><span>Construction subtotal</span><strong>${money(cost.constructionSubtotal)}</strong></div><div><span>Contingency</span><strong>${money(cost.contingency)}</strong></div><div><span>Services</span><strong>${money(cost.services)}</strong></div><div><span>External</span><strong>${money(cost.external)}</strong></div><div><span>Complete total</span><strong>${money(cost.total)}</strong></div></div><p class="planning-status">${cost.complete ? "Complete priced scope" : `Incomplete: ${escape(cost.missingComponentIds.join(", ") || "resolve the listed issues")}`} · Range not calibrated</p>
    <section class="planning-section"><h2>Packages</h2><p>Provisional package assumptions require engineer review.</p><div class="planning-toolbar">${view.recipes.map((recipe) => `<button type="button" data-action="add-package" data-kind="${escape(recipe.kind)}">Add ${escape(recipe.name)}</button>`).join("")}</div>${packageMarkup(scenario, cost)}</section>
    <section class="planning-section"><h2>Custom construction scope</h2><button type="button" data-action="add-custom">Add custom item</button>${customMarkup(scenario, cost)}</section>
    <section class="planning-section"><h2>Allowances</h2><div class="planning-table-wrap"><table><thead><tr><th>Allowance</th><th>Use</th><th>Percent</th><th>Status</th><th>Amount</th></tr></thead><tbody>${allowanceRows}</tbody></table></div></section>
    <section class="planning-section"><h2>External scope decisions</h2>${external}</section>
    <section class="planning-section"><h2>Compare scenarios</h2><select data-field="compare-select">${option("", "Select another scenario", !view.compareId)}${compareOptions}</select>${comparison}</section>
    <section class="planning-section"><h2>Engineer review</h2><p>Review status: ${escape(getScenarioReviewStatus(scenario))}. Check geometry, section, quantity, source price, excluded work, allowances and external scope.</p><div class="planning-grid">${field("Reviewer", "reviewer", scenario.review?.reviewer ?? "")}${field("Review date", "review-date", scenario.review?.date ?? new Date().toISOString().slice(0, 10), "", "date")}</div><label class="planning-field"><span>Review notes</span><textarea data-field="review-notes">${escape(scenario.review?.notes ?? "")}</textarea></label><button type="button" data-action="review">Record review</button></section>
    <details class="planning-issues"><summary>Issues and missing scope (${cost.issues.length})</summary><ul>${cost.issues.map((issue) => `<li>${escape(issue.message)}</li>`).join("")}</ul></details>`;
}

export function renderPlanningWorkspace(root: HTMLElement, view: PlanningViewModel) {
  if (view.state !== "NE" && view.state !== "CO") { root.innerHTML = `<div class="planning-panel"><h1>Planning</h1><p>The Planning pilot is available for Nebraska and Colorado. ${escape(view.state)} is not included in this pilot.</p></div>`; return; }
  root.innerHTML = `<div class="planning-panel"><header class="planning-header"><div><h1>Planning</h1><p>State-specific provisional packages and local scenario workspaces</p></div><div class="planning-toolbar"><button type="button" data-action="save" ${!view.dirty || view.readOnly ? "disabled" : ""}>Save</button><button type="button" data-action="export-json" ${!view.workspace ? "disabled" : ""}>Recovery JSON</button><button type="button" data-action="import-json">Import JSON</button><input type="file" accept="application/json,.json" data-field="import-file" hidden></div></header><p class="planning-message" role="status">${escape(view.message || (view.persistent ? "Saved in this browser" : "Browser storage is unavailable; export JSON for recovery"))}</p>${view.readOnly ? `<div class="planning-card"><strong>Read only: another tab is editing this workspace.</strong> <button type="button" data-action="take-over">Take over editing</button></div>` : ""}<div class="planning-toolbar"><label>Workspace <select data-field="workspace-select">${view.workspaces.map((entry) => option(entry.workspaceId, entry.name, entry.workspaceId === view.workspace?.workspaceId)).join("")}</select></label><button type="button" data-action="create-workspace">New workspace</button></div><fieldset class="planning-editing" ${view.readOnly ? "disabled" : ""}>${view.workspace ? view.scenario && view.cost ? scenarioMarkup(view) : `<div class="planning-card"><h2>${escape(view.workspace.name)}</h2><p>Create a scenario to begin a state-specific estimate.</p><button type="button" data-action="create-scenario">New scenario</button></div>` : `<div class="planning-card"><p>Create a named workspace to save scenarios for ${escape(view.state)}.</p></div>`}</fieldset></div>`;
}
