import type { PackageDefinition, PlanningScenario, PlanningWorkspace, ScenarioComparison, ScenarioCostResult } from "../../planning/types";
import { buildPlannerEstimate, comparePlannerEstimates } from "../../planning/plannerPresentation";

export interface PlanningViewModel {
  state: string;
  workspace: PlanningWorkspace | null;
  workspaces: PlanningWorkspace[];
  scenario: PlanningScenario | null;
  cost: ScenarioCostResult | null;
  comparison: ScenarioComparison | null;
  compareId: string;
  recipes: readonly PackageDefinition[];
  message: string;
  dirty: boolean;
  busy: boolean;
  readOnly: boolean;
  persistent: boolean;
  handoffPersistent?: boolean;
  handoffPreview?: { projectName: string; pricedSubtotal: number; unresolved: string[]; excludedScope: string[]; errors: string[] } | null;
  updatePreview?: { instanceId: string; beforeAmount: number | null; afterAmount: number | null; beforeLabel: string; afterLabel: string } | null;
}

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const money = (value: number | null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const number = (value: number | null | undefined) => value === null || value === undefined ? "" : String(value);
const option = (value: string, label: string, selected: boolean) => `<option value="${escape(value)}" ${selected ? "selected" : ""}>${escape(label)}</option>`;
const field = (label: string, fieldName: string, value: unknown, more = "", type = "text") => `<label class="planning-field"><span>${escape(label)}</span><input type="${type === "number" ? "text" : type}" ${type === "number" ? 'inputmode="decimal"' : ""} data-field="${fieldName}" ${more} value="${escape(value)}"></label>`;

function packageMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  return scenario.packages.map((instance) => {
    const components = cost.components.filter((entry) => entry.instanceId === instance.instanceId);
    const parameters = instance.definition.parameters.map((parameter) => {
      const override = instance.parameterOverrides[parameter.key];
      return `<label class="planning-field"><span>${escape(parameter.label)} (${escape(parameter.unit)})</span><input type="text" inputmode="decimal" data-field="parameter" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" value="${escape(number(override ? override.value : parameter.defaultValue))}"><small>Default: ${escape(number(parameter.defaultValue))}. ${escape(parameter.assumption.description)}</small>${override ? `<input type="text" aria-label="Reason for ${escape(parameter.label)}" data-field="override-reason" data-instance-id="${escape(instance.instanceId)}" data-key="${escape(parameter.key)}" data-kind="parameter" value="${escape(override.reason)}">` : ""}</label>`;
    }).join("");
    const rows = components.map((component) => {
      const snapshot = instance.rateSnapshots[component.role];
      const override = instance.rateOverrides[component.role];
      const quantity = instance.quantityOverrides[component.role];
      const price = component.rateBasis?.kind === "ne_annual" ? `NDOT annual average ${escape(component.rateBasis.periodStart)}–${escape(component.rateBasis.periodEnd)}` : component.rateBasis?.kind === "co_contract_median" ? `CDOT cost-book awarded median across ${component.rateBasis.contracts.length} contracts` : component.rateBasis?.kind === "manual" ? `Manual: ${escape(component.rateBasis.reason)}` : "No price basis";
      const rateControls = component.binding ? scenario.state === "NE" ? `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}"><label class="planning-field"><span>NDOT report series</span><select data-rate="series">${option("calendar_year", "Calendar year", snapshot?.kind !== "ne_annual" || snapshot.reportSeries === "calendar_year")}${option("july_june", "July–June", snapshot?.kind === "ne_annual" && snapshot.reportSeries === "july_june")}</select></label>${field("Report start (optional)", "rate-period-start", snapshot?.kind === "ne_annual" ? snapshot.periodStart : "", `data-rate="period-start"`, "date")}${field("Report end (optional)", "rate-period-end", snapshot?.kind === "ne_annual" ? snapshot.periodEnd : "", `data-rate="period-end"`, "date")}</div>` : `<div class="planning-grid planning-rate-controls" data-rate-instance="${escape(instance.instanceId)}" data-rate-role="${escape(component.role)}">${field("CDOT from date", "rate-from", snapshot?.kind === "co_contract_median" ? snapshot.requestedFrom : "", `data-rate="from"`, "date")}${field("CDOT through date", "rate-to", snapshot?.kind === "co_contract_median" ? snapshot.requestedTo : "", `data-rate="to"`, "date")}${field("Districts (comma separated)", "rate-districts", snapshot?.kind === "co_contract_median" ? snapshot.districts.join(", ") : "", `data-rate="districts"`)}${field("Source IDs (comma separated)", "rate-sources", snapshot?.kind === "co_contract_median" ? snapshot.requestedSourceIds.join(", ") : "", `data-rate="sources"`)}</div>` : "";
      const attributes = `data-instance-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}"`;
      const removed = !!instance.exclusions[component.role];
      const basis = component.rateBasis?.kind === "manual" ? "Manual rate" : component.rateBasis?.kind === "ne_annual" ? "NDOT annual average" : component.rateBasis?.kind === "co_contract_median" ? "CDOT awarded median" : "Price required";
      const evidence = snapshot ? snapshot.kind === "ne_annual" ? `${snapshot.sourceDescription}; ${snapshot.periodStart}/${snapshot.periodEnd}; ${snapshot.sourceUrl}; ${snapshot.sourceLocator}; inflation ${snapshot.inflation.availability}` : `${snapshot.actualFrom}/${snapshot.actualTo}; ${snapshot.contracts.length} contracts; inflation ${snapshot.inflation.availability}` : "No exact source rate available.";
      return `<tr class="planning-component planning-${escape(component.status)}"><td>${escape(component.description)}</td><td>${escape(number(component.quantity))} ${escape(component.unit)}</td><td>${money(component.rate)}</td><td>${money(component.extendedCost)}</td><td>${basis}<details data-detail="evidence-${escape(component.componentId)}"><summary>Source evidence</summary><p>${price}</p><small>${escape(component.binding?.agencyItemId ?? "Manual scope")}; ${escape(evidence)}</small>${component.issues.map((issue) => `<p>${escape(issue.message)}</p>`).join("")}${rateControls}${component.binding ? `<button type="button" class="planning-link" data-action="refresh-rate" data-id="${escape(instance.instanceId)}" data-role="${escape(component.role)}">Apply selected source rate</button>` : ""}</details></td><td><span class="planning-scope-state">${removed ? "Removed" : "Included"}</span><small>${component.status === "excluded" ? "" : escape(component.status.replace(/_/g, " "))}</small></td></tr>
        <tr class="planning-edit-row"><td colspan="6"><details class="planning-row-editor" data-detail="edit-${escape(component.componentId)}"><summary aria-label="Edit ${escape(component.description)}">Edit</summary><div class="planning-grid"><label class="planning-field"><span>Scope</span><select data-field="component-scope" ${attributes}>${option("included", "Included", !removed)}${option("removed", "Removed", removed)}</select></label>${removed ? field("Why is this work removed?", "exclusion-reason", instance.exclusions[component.role]?.reason, attributes) : ""}${field("Quantity override (blank uses default)", "quantity", number(quantity?.value), attributes, "number")}${quantity ? field("Why change the quantity?", "override-reason", quantity.reason, `${attributes} data-kind="quantity"`) : ""}${field("Manual unit price (blank uses source)", "rate", number(override?.value), attributes, "number")}${override ? field("Why change the unit price?", "override-reason", override.reason, `${attributes} data-kind="rate"`) : ""}</div><small>Default quantity: ${escape(number(component.originalQuantity))} ${escape(component.unit)}.${removed ? ` Section effect: ${escape(instance.exclusions[component.role]?.sectionEffect)}` : ""}</small></details></td></tr>`;
    }).join("");
    return `<section class="planning-card"><div class="planning-card-heading"><div><h3>${["resurfacing", "reconstruction", "path"].includes(instance.definition.kind) ? "Base package" : "Optional element"}: ${escape(instance.definition.name)}</h3><p>Provisional ${escape(instance.definition.version)}</p></div>${["sidewalk", "curb_gutter"].includes(instance.definition.kind) ? "" : `<button type="button" class="planning-link" data-action="remove-package" data-id="${escape(instance.instanceId)}">Remove</button>`}</div><details data-detail="package-${escape(instance.instanceId)}"><summary>Geometry, section and assumptions</summary><div class="planning-grid">${parameters}</div><ul>${instance.definition.assumptions.map((assumption) => `<li>${escape(assumption.description)}</li>`).join("")}</ul><p>Excluded by recipe: ${escape(instance.definition.exclusions.join("; "))}</p></details><div class="planning-table-wrap" tabindex="0" role="region" aria-label="Scrollable cost review table"><table><thead><tr><th>Work</th><th>Quantity</th><th>Unit price</th><th>Amount</th><th>Basis</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
  }).join("");
}

function customMarkup(scenario: PlanningScenario, cost: ScenarioCostResult) {
  if (!scenario.customComponents.length) return "";
  const rows = scenario.customComponents.map((component) => {
    const calculated = cost.components.find((entry) => entry.componentId === component.componentId);
    const attributes = `data-id="${escape(component.componentId)}"`;
    return `<tr class="planning-component planning-${escape(calculated?.status ?? "unpriced")}"><td>${escape(component.description)}</td><td>${escape(number(component.quantity))} ${escape(component.unit)}</td><td>${money(component.unitRate)}</td><td>${money(calculated?.extendedCost ?? null)}</td><td>Manual / custom<details data-detail="custom-evidence-${escape(component.componentId)}"><summary>Source evidence</summary><p>${escape(component.reason)}</p></details></td><td>${component.exclusion ? "Removed" : "Included"}<small>${escape(calculated?.status ?? "unpriced")}</small></td></tr><tr class="planning-edit-row"><td colspan="6"><details class="planning-row-editor" data-detail="custom-edit-${escape(component.componentId)}"><summary aria-label="Edit ${escape(component.description)}">Edit</summary><div class="planning-grid">${field("Description", "custom-description", component.description, attributes)}${field("Quantity", "custom-quantity", number(component.quantity), attributes, "number")}${field("Unit price", "custom-unitRate", number(component.unitRate), attributes, "number")}${field("Reason / source", "custom-reason", component.reason, attributes)}<label class="planning-field"><span>Scope</span><select data-field="custom-scope" ${attributes}>${option("included", "Included", !component.exclusion)}${option("removed", "Removed", !!component.exclusion)}</select></label>${component.exclusion ? field("Why is this work removed?", "custom-exclusion-reason", component.exclusion.reason, attributes) : ""}</div><button type="button" class="planning-link" data-action="remove-custom" ${attributes} aria-label="Remove ${escape(component.description)}">Remove</button></details></td></tr>`;
  }).join("");
  return `<section class="planning-card"><h3>Other work</h3><div class="planning-table-wrap" tabindex="0" role="region" aria-label="Scrollable cost review table"><table><thead><tr><th>Work</th><th>Quantity</th><th>Unit price</th><th>Amount</th><th>Basis</th><th>Status</th></tr></thead><tbody>${rows}</tbody></table></div></section>`;
}

function parameterValue(instance: PlanningScenario["packages"][number] | undefined, key: string) {
  if (!instance) return null;
  const override = instance.parameterOverrides[key];
  return override ? override.value : instance.definition.parameters.find((parameter) => parameter.key === key)?.defaultValue ?? null;
}

const packageLabel = (kind: string) => ({ resurfacing: "Asphalt resurfacing", reconstruction: "Concrete reconstruction", path: "Concrete path", sidewalk: "Concrete sidewalk", curb_gutter: "Curb and gutter" })[kind] ?? kind;

function projectElementsMarkup(view: PlanningViewModel, base: PlanningScenario["packages"][number] | undefined) {
  const scenario = view.scenario!;
  const elements = scenario.packages.filter((instance) => ["sidewalk", "curb_gutter"].includes(instance.definition.kind));
  const choices = view.recipes.filter((recipe) => base && (recipe.kind === "sidewalk" || recipe.kind === "curb_gutter" && base.definition.kind === "resurfacing") && !elements.some((instance) => instance.definition.kind === recipe.kind));
  const menu = choices.length ? `<details class="planning-element-menu"><summary>Add project element</summary><div class="planning-element-options">${choices.map((recipe) => `<button type="button" data-action="add-package" data-kind="${escape(recipe.kind)}" ${view.busy ? "disabled" : ""}><strong>${recipe.kind === "sidewalk" ? "Sidewalk" : "Curb and gutter"}</strong></button>`).join("")}</div></details>` : "";
  const rows = elements.map((instance) => {
    const sidewalk = instance.definition.kind === "sidewalk";
    const name = sidewalk ? "Sidewalk" : "Curb and gutter";
    const attributes = `data-instance-id="${escape(instance.instanceId)}"`;
    const components = view.cost!.components.filter((component) => component.instanceId === instance.instanceId && component.category === "construction" && component.status !== "excluded");
    const priced = components.filter((component) => component.status === "priced" && component.extendedCost !== null);
    const subtotal = priced.reduce((sum, component) => sum + component.extendedCost!, 0);
    const complete = components.length > 0 && priced.length === components.length && Number.isFinite(subtotal);
    const costLabel = !components.length ? "No included work" : complete ? money(subtotal) : priced.length && Number.isFinite(subtotal) ? `${money(subtotal)} partial · price pending` : "Price pending";
    const length = parameterValue(instance, "lengthMiles");
    const sideCount = parameterValue(instance, "sides");
    const sides = sideCount === 1 ? "One side" : sideCount === 2 ? "Both sides" : "Sides pending";
    const width = parameterValue(instance, "widthFt");
    const ramps = parameterValue(instance, "rampCount");
    const scope = `${sides} · ${length === null ? "Length pending" : `${number(length)} mi`}${sidewalk ? ` · ${width === null ? "Width pending" : `${number(width)} ft wide`} · ${ramps === null ? "Ramps pending" : `${number(ramps)} ramps`}` : ""}`;
    const inputs = `<label class="planning-field"><span>${name} sides</span><select data-field="${sidewalk ? "sidewalk-sides" : "curb-sides"}" ${attributes}>${option("1", "One side", parameterValue(instance, "sides") === 1)}${option("2", "Both sides", parameterValue(instance, "sides") === 2)}</select></label>${sidewalk ? `${field("Width per side (feet)", "sidewalk-width", number(parameterValue(instance, "widthFt")), attributes, "number")}${field("Approximate curb ramp count", "ramp-count", number(parameterValue(instance, "rampCount")), attributes, "number")}` : ""}`;
    return `<details class="planning-element-row" data-detail="element-${escape(instance.instanceId)}"><summary><span class="planning-element-name">${name}</span><span class="planning-element-scope">${escape(scope)}</span><span class="planning-element-cost" aria-label="${escape(name)} direct construction cost">${escape(costLabel)}</span><button type="button" class="project-line-remove-button planning-element-remove" data-action="remove-package" data-id="${escape(instance.instanceId)}" aria-label="Remove ${name}" title="Remove ${name}"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M9 3h6l1 2h4v2H4V5h4l1-2Z" /><path d="M6 9h12l-1 12H7L6 9Zm4 2v8h2v-8h-2Zm4 0v8h2v-8h-2Z" /></svg></button></summary><div class="planning-element-editor"><div class="planning-grid">${inputs}</div><p class="planning-muted">${sidewalk ? "Driveway crossings and intermediate crossing work require engineer review." : "New curb installation. Existing curb removal is excluded."}</p></div></details>`;
  }).join("");
  const empty = !elements.length && !base ? `<p class="planning-muted">Choose an improvement to add project elements.</p>` : "";
  return `<section class="planning-section planning-elements"><div class="planning-elements-heading"><h2>Additional project elements</h2>${menu}</div>${rows}${empty}</section>`;
}

function scenarioMarkup(view: PlanningViewModel) {
  const scenario = view.scenario!;
  const cost = view.cost!;
  const estimate = buildPlannerEstimate(scenario, cost);
  const base = scenario.packages.find((instance) => ["resurfacing", "reconstruction", "path"].includes(instance.definition.kind));
  const baseId = `data-instance-id="${escape(base?.instanceId ?? "")}"`;
  const section = base ? base.definition.parameters.filter((parameter) => ["thicknessIn", "baseDepthIn"].includes(parameter.key)).map((parameter) => `${number(parameterValue(base, parameter.key))} inch ${parameter.key === "thicknessIn" ? (base.definition.kind === "resurfacing" ? "asphalt" : "concrete") : "base"}`).join(" over ") : "Choose an improvement to start.";
  const external = scenario.externalScopes.map((scope) => `<div class="planning-impact"><label class="planning-field"><span>${scope.scopeId === "right_of_way" ? "Property acquisition" : "Major utility relocation"}</span><select data-field="external-decision" data-id="${escape(scope.scopeId)}">${option("none_assumed", "Not expected", scope.decision === "none_assumed")}${option("unassessed", "Possible / unknown", scope.decision === "unassessed")}${option("manual", "Known impact", scope.decision === "manual")}</select></label>${scope.decision === "manual" ? `<details><summary>Known cost${scope.amount !== null ? `: ${money(scope.amount)}` : " (if available)"}</summary>${field("Estimated amount", "external-amount", number(scope.amount), `data-id="${escape(scope.scopeId)}"`, "number")}${field("Basis (optional)", "external-reason", scope.reason, `data-id="${escape(scope.scopeId)}"`)}</details>` : ""}</div>`).join("");
  const externalAdvanced = scenario.externalScopes.filter((scope) => scope.reason && scope.decision !== "unassessed").map((scope) => `<p>${scope.scopeId === "right_of_way" ? "Property acquisition" : "Major utility relocation"}: ${escape(scope.reason)}</p>`).join("");
  const allowanceRows = scenario.allowances.map((allowance) => {
    const calculated = cost.allowances.find((entry) => entry.allowanceId === allowance.allowanceId);
    return `<tr><td>${escape(allowance.name)}<details data-detail="allowance-${escape(allowance.allowanceId)}"><summary>Edit / calculation basis</summary><small>${escape(allowance.assumption.description)} Base: ${escape(allowance.base.kind.replace(/_/g, " "))}; calculated base ${money(calculated?.baseAmount ?? null)}.</small><div class="planning-grid"><label class="planning-field"><span>Included</span><input aria-label="Include ${escape(allowance.name)}" type="checkbox" data-field="allowance-enabled" data-id="${escape(allowance.allowanceId)}" ${allowance.enabled ? "checked" : ""}></label>${field("Percent", "allowance-percent", number(allowance.percent), `data-id="${escape(allowance.allowanceId)}"`, "number")}${allowance.overrideReason ? field("Why change this allowance?", "allowance-reason", allowance.overrideReason, `data-id="${escape(allowance.allowanceId)}"`) : ""}</div></details></td><td>${escape(number(allowance.percent))}%</td><td>${money(calculated?.amount ?? null)}</td><td>${allowance.enabled ? escape(calculated?.status ?? "unpriced") : "Removed"}</td></tr>`;
  }).join("");
  const other = view.workspace!.scenarios.find((entry) => entry.scenarioId === view.compareId);
  const comparisonEstimate = other && view.comparison ? buildPlannerEstimate(other, view.comparison.right) : null;
  const difference = comparisonEstimate ? comparePlannerEstimates(estimate, comparisonEstimate) : null;
  const comparison = comparisonEstimate ? `<div class="planning-comparison"><strong>${escape(other!.name)}: ${money(comparisonEstimate.amount)}</strong><p>${difference === null ? "Included or excluded work differs. Review coverage before comparing costs." : `Difference for the same included work: ${money(difference)}`}</p></div>` : "";
  const updates = scenario.packages.filter((instance) => view.recipes.some((recipe) => recipe.kind === instance.definition.kind && recipe.version !== instance.definition.version)).map((instance) => `<details class="planning-package-update"><summary>${escape(packageLabel(instance.definition.kind))}: package update available</summary><p>Saved prices and quantities stay frozen until you apply a reviewed update.</p><button type="button" data-action="preview-package-update" data-id="${escape(instance.instanceId)}">Preview revised package</button>${view.updatePreview?.instanceId === instance.instanceId ? `<p>Current ${escape(view.updatePreview.beforeLabel)}: ${money(view.updatePreview.beforeAmount)}<br>Revised ${escape(view.updatePreview.afterLabel)}: ${money(view.updatePreview.afterAmount)}</p><button type="button" data-action="adopt-package-update" data-id="${escape(instance.instanceId)}">Use revised package</button>` : ""}</details>`).join("");
  const handoff = view.handoffPreview;
  const handoffMarkup = `<section class="planning-handoff"><h3>Continue in Project</h3><p>Create an independent Project draft for item-level estimating.</p><details data-detail="handoff-confirmation"><summary>${scenario.handoffIntent?.status === "complete" ? "Linked Project" : "Create Project from alternative"}</summary>${field("Destination Project name", "handoff-name", handoff?.projectName ?? `${view.workspace!.name} / ${scenario.name}`)}<dl><div><dt>State</dt><dd>${scenario.state === "NE" ? "Nebraska" : "Colorado"}</dd></div><div><dt>Priced subtotal</dt><dd>${money(handoff?.pricedSubtotal ?? null)}</dd></div></dl><p><strong>Work to resolve (${handoff?.unresolved.length ?? 0})</strong></p>${handoff?.unresolved.length ? `<ul>${handoff.unresolved.map((name) => `<li>${escape(name)}</li>`).join("")}</ul>` : `<p>${handoff ? "No unresolved required work." : "Preparing handoff preview."}</p>`}<p>Planning allowances stay frozen at their calculated amounts and original bases. Frozen Planning contingency becomes a separate Other Costs line; Project contingency starts at 0%.</p><p><strong>Excluded / none assumed:</strong> ${escape(handoff?.excludedScope.join("; ") || "No explicit exclusions.")}</p><p>Planning retains this alternative. Project edits do not change Planning or recalculate frozen allowances.</p>${handoff?.errors.length ? `<ul class="planning-notices">${handoff.errors.map((error) => `<li>${escape(error)}</li>`).join("")}</ul>` : ""}${!view.handoffPersistent ? `<p>Browser persistence is required to create a Project.</p>` : ""}<button type="button" data-action="create-project-handoff" ${view.readOnly || view.busy || !view.handoffPersistent || !handoff || handoff.errors.length ? "disabled" : ""}>${scenario.handoffIntent?.status === "pending" ? "Resume Project handoff" : scenario.handoffIntent?.status === "complete" ? "Open linked Project" : "Create Project from alternative"}</button>${scenario.handoffIntent?.status === "complete" ? `<button type="button" data-action="create-another-project-handoff" class="secondary-button" ${view.readOnly || view.busy || !view.handoffPersistent || !handoff || handoff.errors.length ? "disabled" : ""}>Create another Project snapshot</button>` : ""}</details></section>`;
  const impactPending = scenario.externalScopes.filter((scope) => scope.decision === "unassessed" || scope.decision === "manual" && scope.amount === null).map((scope) => scope.scopeId === "right_of_way" ? "property acquisition" : "major utility relocation");
  return `<div class="planning-toolbar planning-alternative"><label class="planning-field"><span>Alternative</span><select data-field="scenario-select">${view.workspace!.scenarios.map((entry) => option(entry.scenarioId, entry.name, entry.scenarioId === scenario.scenarioId)).join("")}</select></label><details class="planning-export"><summary>Export for engineer</summary><div class="planning-export-options"><button type="button" data-action="export-csv">Current alternative CSV</button><button type="button" data-action="export-json">Planning project JSON</button></div></details></div>
    <div class="planning-layout"><div class="planning-main">
    <section class="planning-section"><h2>Project basics</h2><div class="planning-grid"><label class="planning-field"><span>Improvement type</span><select data-field="base-kind">${option("", "Choose improvement", !base)}${view.recipes.filter((recipe) => ["resurfacing", "reconstruction", "path"].includes(recipe.kind)).map((recipe) => option(recipe.kind, packageLabel(recipe.kind), recipe.kind === base?.definition.kind)).join("")}</select></label>${field("Length (miles)", "planner-length", number(parameterValue(base, "lengthMiles")), `${baseId} ${!base ? "disabled" : ""}`, "number")}${field(base?.definition.kind === "path" ? "Path width (feet)" : "Roadway width (feet)", "planner-width", number(parameterValue(base, "widthFt")), `${baseId} ${!base ? "disabled" : ""}`, "number")}</div></section>
    <section class="planning-section"><h2>Base package</h2><p>${escape(base ? packageLabel(base.definition.kind) : "No improvement selected")} · ${escape(section)}</p>${base ? `<p>${escape(base.definition.components.map((component) => component.description).join("; "))}.</p><details data-detail="quantity-assumptions"><summary>See quantity assumptions</summary><ul>${base.definition.parameters.map((parameter) => `<li>${escape(parameter.label)}: ${escape(number(parameterValue(base, parameter.key)))} ${escape(parameter.unit)}</li>`).join("")}</ul></details>` : ""}</section>
    ${projectElementsMarkup(view, base)}
    <section class="planning-section planning-impacts"><h2>Major project impacts</h2><p class="planning-muted">Choose what is known. An engineer can assess uncertain costs later.</p><div class="planning-grid">${external}</div></section>
    </div><aside class="planning-estimate planning-section" aria-label="Estimate summary"><h2>Estimate summary</h2><span class="planning-provisional">Provisional planning prices</span><dl><div><dt>Priced construction</dt><dd>${money(estimate.construction)}</dd></div><div><dt>Other project costs</dt><dd>${money(estimate.otherProjectCosts)}</dd></div><div class="planning-estimate-total"><dt>${escape(estimate.amountLabel)}</dt><dd>${money(estimate.amount)}</dd></div></dl>${impactPending.length ? `<p class="planning-scope"><strong>Still to assess:</strong> ${escape(impactPending.join("; "))}.</p>` : ""}<p class="planning-muted">Order-of-magnitude estimate. Engineer review is required.</p><label class="planning-field"><span>Compare with</span><select data-field="compare-select">${option("", "Select alternative", !view.compareId)}${view.workspace!.scenarios.filter((entry) => entry.scenarioId !== scenario.scenarioId).map((entry) => option(entry.scenarioId, entry.name, view.compareId === entry.scenarioId)).join("")}</select></label>${comparison}</aside></div>
    <section class="planning-section"><h2>Assumptions and next steps</h2><details class="planning-advanced"><summary>Estimate details</summary><div class="planning-advanced-content"><div class="planning-grid">${field("Alternative name", "name", scenario.name)}</div><label class="planning-field"><span>Notes</span><textarea data-field="notes">${escape(scenario.notes)}</textarea></label>${updates}${packageMarkup(scenario, cost)}${customMarkup(scenario, cost)}<h3>Other costs and contingency</h3><div class="planning-table-wrap" tabindex="0" role="region" aria-label="Scrollable cost review table"><table><thead><tr><th>Cost</th><th>Percent</th><th>Amount</th><th>Status</th></tr></thead><tbody>${allowanceRows}</tbody></table></div>${externalAdvanced}</div></details>${handoffMarkup}</section>`;
}

export function renderPlanningWorkspace(root: HTMLElement, view: PlanningViewModel) {
  if (view.state !== "NE" && view.state !== "CO") { root.innerHTML = `<div class="planning-panel"><h1>Planning</h1><p>The Planning pilot is available for Nebraska and Colorado.</p></div>`; return; }
  const creation = `<div class="planning-grid">${field("Planning project name", "new-project-name", "")}<button type="button" data-action="create-workspace" ${view.busy || view.readOnly ? "disabled" : ""}>Create planning project</button></div>`;
  const saved = view.message || (view.dirty ? "Unsaved changes" : view.persistent ? "Saved in this browser" : "Browser storage unavailable; export a Planning project JSON file");
  root.innerHTML = `<div class="planning-panel"><header class="planning-header"><div><h1>Planning${view.workspace ? ` · ${escape(view.workspace.name)}` : ""}</h1><p>${view.state === "NE" ? "Nebraska" : "Colorado"} planning estimate</p></div><details class="planning-actions"><summary>Planning actions</summary><div class="planning-actions-content"><label class="planning-field"><span>Planning project</span><select data-field="workspace-select">${view.workspaces.map((entry) => option(entry.workspaceId, entry.name, entry.workspaceId === view.workspace?.workspaceId)).join("")}</select></label>${view.workspace ? `${creation}<button type="button" data-action="duplicate" ${!view.scenario ? "disabled" : ""}>Create comparison alternative</button>` : ""}<button type="button" data-action="save" ${!view.dirty || view.readOnly ? "disabled" : ""}>Save changes</button><button type="button" data-action="import-json">Import planning project JSON</button></div></details><input type="file" accept="application/json,.json" data-field="import-file" hidden></header><p class="planning-message" role="status">${escape(saved)}</p>${view.readOnly ? `<div class="planning-card"><strong>Read only: another tab is editing this planning project.</strong> <button type="button" data-action="take-over">Take over editing</button></div>` : ""}<fieldset class="planning-editing" ${view.readOnly ? "disabled" : ""}>${view.workspace ? view.scenario && view.cost ? scenarioMarkup(view) : `<div class="planning-card"><p>Add an alternative to start estimating.</p><button type="button" data-action="create-scenario">Create Alternative A</button></div>` : `<section class="planning-section"><h2>Create a planning project</h2><p>Start with a project name. Then select the improvement and approximate length.</p>${creation}</section>`}</fieldset></div>`;
}
